name: spring-boot-postgresql-crud

services:
  postgres:
    image: postgres:16-alpine
    container_name: productdb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d productdb"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
